[build]
builder = "nixpacks"
buildCommand = """
rm -rf node_modules/.cache || true
npm ci && npm run build
"""
startCommand = "npm run preview"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure" 