[build]
builder = "nixpacks"
buildCommand = "npm ci"
startCommand = "npm run preview"

[deploy]
startCommand = "npm run preview"
restartPolicyType = "on_failure"
healthcheckPath = "/"
healthcheckTimeout = 100