[build]
builder = "ubuntu"
buildCommand = """
curl -fsSL https://deb.nodesource.com/setup_18.x | bash - && \
apt-get install -y nodejs && \
npm install && \
npm run build
"""
startCommand = "npm run preview -- --host 0.0.0.0"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure" 