[build]
builder = "nixpacks"
buildCommand = "npm install && npm run build"
startCommand = "npm run serve -- --host 0.0.0.0"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"