[build]
builder = "nixpacks"
buildCommand = "pwd && npm install && npm run build"
startCommand = "pwd && npm run preview -- --host 0.0.0.0"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure" 