[build]
builder = "nixpacks"
buildCommand = "npm install --no-cache && npm run build"
startCommand = "npm run preview -- --host 0.0.0.0"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure" 