[build]
builder = "nixpacks"
buildCommand = """
cd server && \
export DATABASE_URL=$(railway variables get DATABASE_URL) && \
npm ci && \
npx prisma generate && \
npx ts-node src/test-connection.ts && \
npx prisma db push
"""

[deploy]
startCommand = "cd server && npm start"
healthcheckPath = "/api/test"
healthcheckTimeout = 100
restartPolicyType = "on_failure"