[build]
builder = "nixpacks"
buildCommand = """
cd server && \
DATABASE_URL=$DATABASE_PUBLIC_URL npm ci && \
DATABASE_URL=$DATABASE_PUBLIC_URL npx prisma generate && \
DATABASE_URL=$DATABASE_PUBLIC_URL npx ts-node src/test-connection.ts && \
DATABASE_URL=$DATABASE_PUBLIC_URL npx prisma db push
"""

[deploy]
startCommand = "cd server && npm start"
healthcheckPath = "/api/test"
healthcheckTimeout = 100
restartPolicyType = "on_failure"