[build]
builder = "nixpacks"
buildCommand = "cd client && npm ci && npm run build"
startCommand = "cd client && npm run preview"

[deploy]
startCommand = "cd server && npm start"
healthcheckPath = "/api/test"
healthcheckTimeout = 100
restartPolicyType = "on_failure"