[build]
builder = "nixpacks"
buildCommand = """
cd server && \
npm install && \
npm run build:prod
"""

[deploy]
startCommand = "cd server && npm start"
healthcheckPath = "/api/test"
healthcheckTimeout = 100
restartPolicyType = "on_failure" 