[build]
builder = "nixpacks"
buildCommand = """
cd server && \
export DATABASE_PASSWORD=$DATABASE_PASSWORD && \
export DATABASE_HOST=$DATABASE_HOST && \
export DATABASE_PORT=$DATABASE_PORT && \
export DATABASE_NAME=$DATABASE_NAME && \
npm ci && \
npx prisma generate && \
npx ts-node src/test-connection.ts && \
npx prisma db push
"""

[deploy]
startCommand = "cd server && npm start"
healthcheckPath = "/api/test"
healthcheckTimeout = 100
restartPolicyType = "on_failure"