[build]
builder = "nixpacks"
buildCommand = """
cd server && \
echo "DATABASE_URL=$RAILWAY_PUBLIC_DATABASE_URL" > .env && \
npm ci && \
npx prisma generate && \
npx ts-node src/test-connection.ts && \
npx prisma db push
"""

[deploy]
startCommand = "cd server && npm start"
healthcheckPath = "/api/test"
healthcheckTimeout = 100
restartPolicyType = "on_failure"