[build]
builder = "nixpacks"
buildCommand = """
pwd && \
npm install --include=dev && \
npm run build && \
npm run prisma:generate && \
npm run prisma:push
"""
startCommand = "pwd && npm start"

[deploy]
healthcheckPath = "/api/test"
healthcheckTimeout = 100
restartPolicyType = "on_failure" 