[build]
builder = "ubuntu"
buildCommand = """
curl -fsSL https://deb.nodesource.com/setup_18.x | bash - && \
apt-get install -y nodejs && \
npm install --include=dev && \
npm install -g typescript prisma && \
tsc -p tsconfig.json && \
prisma generate && \
prisma db push
"""
startCommand = "node dist/index.js"

[deploy]
healthcheckPath = "/api/test"
healthcheckTimeout = 100
restartPolicyType = "on_failure" 