[build]
builder = "nixpacks"
buildCommand = "npm install && npx prisma generate && npx prisma db push"
startCommand = "npm start"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"