[build]
builder = "nixpacks"
buildCommand = """
npm install --production=false && \
npm run build && \
npx prisma generate && \
npx prisma db push
"""
startCommand = "node dist/index.js"

[deploy]
healthcheckPath = "/api/test"
healthcheckTimeout = 100
restartPolicyType = "on_failure" 