[build]
builder = "nixpacks"
buildCommand = """
npm install --include=dev && \
npx tsc && \
npx prisma generate && \
npx prisma db push
"""
startCommand = "npm start"

[deploy]
healthcheckPath = "/api/test"
healthcheckTimeout = 100
restartPolicyType = "on_failure" 