[build]
builder = "nixpacks"
buildCommand = """
npm install --no-cache && \
npm run build && \
npx --no-install prisma generate && \
npx --no-install prisma db push && \
npx --no-install prisma db seed
"""
startCommand = "npm start"

[deploy]
healthcheckPath = "/api/test"
healthcheckTimeout = 100
restartPolicyType = "on_failure" 