[build]
builder = "nixpacks"
buildCommand = """
npm install && \
npm run build && \
npx prisma db push
"""
startCommand = "npm start"

[deploy]
healthcheckPath = "/api/test"
healthcheckTimeout = 100
restartPolicyType = "on_failure" 