[build]
builder = "nixpacks"
buildCommand = """
npm install --no-cache && \
npm run build && \
npx prisma generate && \
npx prisma db push && \
npx prisma db seed
"""
startCommand = "npm start"

[deploy]
healthcheckPath = "/api/test"
healthcheckTimeout = 100
restartPolicyType = "on_failure" 