[build]
builder = "nixpacks"
buildCommand = """
npm install --include=dev && \
NODE_ENV=development npx tsc -p tsconfig.json && \
npx prisma generate && \
npx prisma db push
"""
startCommand = "node dist/index.js"

[deploy]
healthcheckPath = "/api/test"
healthcheckTimeout = 100
restartPolicyType = "on_failure" 