[build]
builder = "nixpacks"
buildCommand = "npm ci"
startCommand = "npm run start"

[deploy]
startCommand = "npm run start"
restartPolicyType = "on_failure"
healthcheckPath = "/api/test"
healthcheckTimeout = 100